---
title: "HaASSaMD"
author: "Robert A. Stevens"
date: "May 9, 2016"
output: html_document
---

http://user2016.org/tutorials/09.html

# Handling and Analyzing Spatial, Spatiotemporal and Movement Data

Edzer Pebesma - Institute for Geoinformatics, University of Muenster

## Tutorial Description

The tutorial will introduce users to the different types of spatial data (points, lines, polygons, rasters) and demonstrate how they are read in R. It will also explain how time series data can be imported, handled and analyzed in R. Then, it will explain the different types of spatiotemporal data and trajectory data, and present ways of importing them and analyzing them.

## Goals

The goals of this tutorial are to make participants familiar with

1. basic R packages for handling spatial data (sp, rgdal, rgeos, raster)

2. basic R packages for time series data analysis (zoo, xts)

3. R packages for spatiotemporal analysis (spacetime, trajectories)

4. spatiotemporal fields (continuously varying phenomena), events, objects, and trajectories, and the meaningfulness of analysis methods on each of these

5. strong referencing in R, and how it allows the integration of di

In addition, participants will be pointed to further resources (R packages, CRAN task views, software papers, scientific literature).

## Tutorial Outline

Using a small number of use cases, following this sequence, the tutorial will illustrate how to

1. import spatial, temporal, and spatiotemporal data in R

2. map these data structures to and from matrix and data.frame objects

3. work with points, lines, polygons, and rasters

4. work with time series of each of these

5. work with space-time events, and moving objects

6. intersect various spacetime objects, e.g. for spatial and/or temporal selection or for spatial, temporal or spatiotemporal aggregation

7. represent higher concepts such as fields, objects, events, trajectories, and aggregations into the classes, and how to carry out meaningful analysis of these

and give users the opportunity to experiment with this material.

The tutorial consists of three one-hour blocks, where 45 mins lecturing/demonstration is followed by 15 mins breaks where participants can try to replicate the analysis, work on their own data, or start small-group discussions.

Prospective planning: 

- first hour: spatial and temporal

- second hour: spatiotemporal, intersections, aggregations

- third hour: movement data, meaningfulness, data integration

## Background Knowledge

Some prior familiarity with handling spatial and/or temporal data is of benefit, but not required. Familiarity with R is assumed.

## Instructor Biography

Edzer Pebesma is professor in geoinformatics since 2007. He is Co-Editor-in-Chief for the Journal of Statistical Software [1] and Computers & Geosciences [2], and associate editor for Spatial Statistics. He is developer and maintainer of several popular package packages for handling and analyzing spatial and spatiotemporal data (sp [3], spacetime [4], trajectories [5], gstat [6]), co-author of the book *Applied Spatial Data Analysis with R*, second edition [7], and active member of the r-sig-geo [8] community. He gives regular tutorials on this topic area, for instance during the yearly geostat [9] summer schools. The tutorial material on analyzing trajectory (movement) data is new.

Edzer’s google scholar page is found here [10].

[1] https://www.jstatsoft.org/index

[2] http://www.journals.elsevier.com/computers-and-geosciences

[3] https://cran.rstudio.com/web/packages/sp/index.html

[4] https://cran.rstudio.com/web/packages/spacetime/index.html

[5] https://cran.rstudio.com/web/packages/trajectories/index.html

[6] https://cran.rstudio.com/web/packages/gstat/index.html

[7] http://www.asdar-book.org

[8] http://markmail.org/search/?q=r-sig-geo

[9] http://geostat-course.org/node

[10] https://scholar.google.de/citations?user=d6jdqdQAAAAJ&hl=en
